# Generated by Django 3.1.7 on 2021-04-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KartuKeluarga',
            fields=[
                ('no_kk', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
