# Generated by Django 3.1.7 on 2021-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistikdesa', '0002_auto_20210403_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartukeluarga',
            name='alamat',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='kecamatan',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='kelurahan',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='kode_pos',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='nama_kk',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='provinsi',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='rt',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='rw',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penduduk',
            name='kewarganegaraan',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
