# Generated by Django 3.1.7 on 2021-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparatur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('position', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
