# Generated by Django 3.1.7 on 2021-03-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aparatur',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='aparatur',
            old_name='position',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='aparatur',
            name='address',
        ),
        migrations.RemoveField(
            model_name='aparatur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aparatur',
            name='phone',
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=1024)),
                ('biography', models.TextField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='profiledesa.aparatur')),
            ],
        ),
    ]
