# Generated by Django 3.1.7 on 2021-03-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0004_auto_20210328_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kepaladesa',
            old_name='is_featured',
            new_name='status',
        ),
        migrations.CreateModel(
            name='Stafdesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=1024)),
                ('biography', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stafdesas', to='profiledesa.aparatur')),
            ],
        ),
    ]
