# Generated by Django 3.1.7 on 2021-03-30 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0005_auto_20210329_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='kepaladesa',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='kepaladesa',
            name='biography',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
