# Generated by Django 3.1.7 on 2021-04-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0006_auto_20210330_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kepaladesa',
            new_name='Aparat',
        ),
        migrations.DeleteModel(
            name='Stafdesa',
        ),
    ]
