# Generated by Django 3.1.7 on 2021-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0007_auto_20210401_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokohMasyarakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_masyarakat', models.CharField(max_length=225)),
                ('Name', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=225)),
                ('address', models.CharField(max_length=1024)),
                ('thumbnail', models.ImageField(default=False, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='aparat',
            name='slug',
            field=models.SlugField(max_length=225),
        ),
    ]
