# Generated by Django 3.1.7 on 2021-04-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0008_auto_20210402_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokohMasyarakat',
        ),
    ]
