# Generated by Django 3.1.7 on 2021-04-07 01:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiledesa', '0009_delete_tokohmasyarakat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparat',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
