# Generated by Django 3.1.7 on 2021-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210329_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
