# Generated by Django 3.1.7 on 2021-03-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210329_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tumbnail',
            new_name='thumbnail',
        ),
    ]
